<a href="https://colab.research.google.com/github/HuyLearnProgram/Data-Science/blob/main/Basic_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

#Creating numpy a from Cratch
zeros, ones, full, arrange, linespace

In [3]:
np.zeros([2,4],dtype="int")

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [4]:
np.ones([3,5],dtype="float")

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.full([2,3],5.3)

array([[5.3, 5.3, 5.3],
       [5.3, 5.3, 5.3]])

In [6]:
np.arange(0,7,2)

array([0, 2, 4, 6])

In [7]:
#Create an array of five values evenly space between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])